language: cpp

compiler:
  - gcc
  - clang

env:
  - AUTOTOOLS=yes
  - AUTOTOOLS=no

script: ./script/cibuild

before_install:
  - sudo pip install cpp-coveralls

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - gem install minitest

after_success:
  - coveralls --exclude sass-spec --exclude sassc --gcov-options '\-lp'