environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
  - Compiler: mingw
    Build: static
  - Compiler: mingw
    Build: shared

install:
  - git clone https://github.com/mgreter/sassc.git --branch feature/build-dll-win-mingw
  - git clone https://github.com/sass/sass-spec.git
  - set SASS_LIBSASS_PATH=c:/projects/libsass
  - gem install minitest
  - ps: |
      if ($env:Compiler -eq "mingw") {
        # Install MinGW.
        $url  = "http://sourceforge.net/projects/mingw-w64/files/"
        $url += "Toolchains%20targetting%20Win64/Personal%20Builds/"
        $url += "mingw-builds/4.9.2/threads-win32/seh/"
        $url += "x86_64-4.9.2-release-win32-seh-rt_v3-rev0.7z/download"
        Invoke-WebRequest -UserAgent wget -Uri $url -OutFile mingw.7z
        &7z x -oC:\ mingw.7z > $null
      }
  - set PATH=%PATH%;C:\mingw64\bin
  - set CC=gcc

build_script:
  - ps: |
      if ($env:Compiler -eq "mingw") {
        mingw32-make
      } else {
        msbuild /m:4 /p:Config=$env:Config FORMAT.sln
      }

test_script:
  - ps: |
      if ($env:Compiler -eq "mingw") {
        mingw32-make test_build
      } else {
        msbuild RUN_TESTS.vcxproj
      }
